name: artifact-link test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "artifact #1" > af1.txt
          echo "artifact numero duo" > af2.md
      - uses: actions/upload-artifact@v4
        name: upload 1
        with:
          name: af1
          path: af1.txt
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        name: upload 2
        with:
          name: af2
          path: af2.md
          if-no-files-found: error

  link:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: beni69/artifact-link@ba373a5a9c7265a0038ec702267e4b938c47f1cc
        with:
          token: ${{ github.token }}
