name: artifact-link test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "artifact #1" > af1.txt
          echo "artifact numero duo" > af2.md
      - uses: actions/upload-artifact@v4
        name: upload 1
        with:
          name: af1
          path: af1.txt
      - uses: actions/upload-artifact@v4
        name: upload 2
        with:
          name: af2
          path: af2.md

  link:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: beni69/artifact-link@v1
        with:
          token: ${{ github.token }}
